## Console settings
# Width
CSNL_WIDTH = 100
CSNL_PLAY_AREA_WIDTH = 65
CSNL_CHARACTER_STATS_WIDTH = CSNL_WIDTH - CSNL_PLAY_AREA_WIDTH
# Height
CSNL_HEIGHT = 50
CSNL_CHARACTER_STATS_HEIGHT = 15

# Tilesets
TILE_INFO = 0x1000


# Dungeon settings
DUNGEON_WIDTH = 200
DUNGEON_HEIGHT = 200

# Tileset
TILESET_PATH = 'data/graphics/default16x16.png'
TILESET_COL = 16
TILESET_ROW = 16

# components/abilities.py
BASE_HP = 20

